export type Organization = {id:string; name:string; kind:'donor'|'charity'|'partner'; description:string; address:string; city:string; contact_email:string; is_verified:boolean; created_at:string};
export type Listing = {id:string; organization_id:string; title:string; description:string; category:string; quantity:number; unit:string; dietary_tags:string[]; allergens:string[]; pickup_start:string; pickup_end:string; address:string; city:string; status:string; meals_estimate:number; organization_name?:string; created_at:string};
export type RouteStop = {id:string; listing_id:string; destination_name:string; destination_address:string; stop_order:number; status:string};
export type Route = {id:string; name:string; volunteer_name?:string; volunteer_email?:string; scheduled_for:string; status:string; distance_km:number; notes:string; stops:RouteStop[]; created_at:string};
export type Impact = {meals_rescued:number; co2_saved_kg:number; water_saved_l:number; listings_completed:number; active_listings:number};
export type Activity = {id:string; actor_name:string; action:string; entity_type:string; entity_id:string; detail:string; created_at:string};
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
async function request<T>(path:string, init?:RequestInit):Promise<T>{ const response=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json',...(init?.headers||{})},...init}); if(!response.ok) throw new Error((await response.json().catch(()=>({detail:'Request failed'}))).detail); return response.json(); }
export const api={ listings:(query='')=>request<Listing[]>(`/api/v1/listings${query}`), listing:(id:string)=>request<Listing>(`/api/v1/listings/${id}`), organizations:()=>request<Organization[]>('/api/v1/organizations'), routes:()=>request<Route[]>('/api/v1/routes'), impact:()=>request<Impact>('/api/v1/impact'), activity:()=>request<Activity[]>('/api/v1/activity'), reservations:()=>request<any[]>('/api/v1/reservations'), createListing:(body:unknown)=>request<Listing>('/api/v1/listings',{method:'POST',body:JSON.stringify(body)}), reserve:(body:unknown)=>request<any>('/api/v1/reservations',{method:'POST',body:JSON.stringify(body)}), claimRoute:(id:string,body:unknown)=>request<Route>(`/api/v1/routes/${id}/claim`,{method:'POST',body:JSON.stringify(body)})};
